// Generated by https://quicktype.io



// Generated by https://quicktype.io

export interface RegisterDataStudent {
    nombres: string;
    apellidos: string;
    correo: string;
    edad: string;
    contrasena: string;
    tipo: string;
    gradoAcademico: string
}

// Generated by https://quicktype.io

export interface RegisterDataTeacher {
    nombres: string;
    apellidos: string;
    correo: string;
    tipo: string;
    precio_ensenianza: string;
    teacherType: string;
    descripcion: string;
    numeroDoc: string;
    foto_perfil: string;
}


export interface LoginData {
    correo: string;
    password: string;
    tipo_usuario: string | undefined;
}

// Generated by https://quicktype.io

export interface LoginResponse {
    mensaje: string;
    rpta: number;
    tipoUsuario: string;
    token: string;
    user: User;
}

export interface User {
    apellidos: string;
    edad: string;
    fecha_creacion: string;
    foto_perfil: null;
    id: string;
    nombres: string;
    tipo_de_usuario: string;
    usuarios_id: string;
    grado_academico: string
}
// Generated by https://quicktype.io

export interface LoginResponseTeacher {
    mensaje: string;
    rpta: number;
    user: UserTeacher;
    token: string;
    tipoUsuario: string;

}

/* prueba */


// Generated by https://quicktype.io

export interface LoginTeacherResponse {
    mensaje: string;
    rpta: number;
    tipoUsuario: string;
    token: string;
    user: { [key: string]: string };
}


// Generated by https://quicktype.io

export interface UserTeacher {
    apellidos: string;//
    correo_contacto: string;
    descripcion: string;
    estado: string;
    fecha_creacion: string;//
    foto_perfil: string;
    id: string;
    nombres: string;//
    numero_documento: string;
    precio_ensenianza: string;
    tipo_de_usuario: string;//
    tipo_profesor: string;
    usuarios_id: string;//
}

/* 
export interface User {
    apellidos: string;
    edad: string;
    fecha_creacion: string;
    foto_perfil: null;
    id: string;
    nombres: string;
    tipo_de_usuario: string;
    usuarios_id: string;
    grado_academico: string
}
*/












// Generated by https://quicktype.io

export interface LoginTeacherResponse2 {
    mensaje: string;
    profesor: Profesor;
    rpta: number;
    tipoUsuario: string;
    token: string;
    user: LoginTeacherResponse2User;
}

export interface Profesor {
    apellidos: string;
    correo_contacto: string;
    descripcion: string;
    estado: string;
    fecha_creacion: string;
    foto_perfil: string;
    id: string;
    nombres: string;
    numero_documento: string;
    precio_ensenianza: string;
    tipo_de_usuario: string;
    tipo_profesor: string;
    user: ProfesorUser;
    usuarios_id: string;
}

export interface ProfesorUser {
    email: string;
    id: string;
    tipo: string;
}

export interface LoginTeacherResponse2User {
    email: string;
    id: string;
    tipo_usuario: string;
}
